### ISSUE TITLE
Connection gets closed

### ISSUE THREAD

**Issue by GHNewbiee** [darold/uri#1]
I run the following command:

```
INSERT INTO table_name (name, icon_path)
    VALUES
('name_1', 'file:///home/GHNewbiee/icon_1.png'),
('name_2', 'file:///home/GHNewbiee/icon_2.png'),
('name_3', 'file:///home/GHNewbiee/icon_3.png');
```
but server closes the connection. Please, advice.

_Note: Files do not exist yet! Same happens if I use any http://... uri._

Tia

**Comment by GHNewbiee** [comment]
I hope the following helps you:

`pg_version: PostgreSQL 10.4 (Ubuntu 10.4-2.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609, 64-bit` on `Linux Mint 18.3`

OmniDB client terminates with:
`SSL SYSCALL error: EOF detected`

DBeaver client terminates with
`SQL Error [08003]: This connection has been closed.`
or sometimes with
`SQL Error [XX000]: ERROR: invalid memory alloc request size 18446744073709551613
  Position: 62`

I also attach the libraries after compilation.

Tia
[compiled_libs_amd64.zip](https://github.com/darold/uri/files/2058699/compiled_libs_amd64.zip)

**Comment by GHNewbiee** [comment]
Using liburi 3.0.1 issued on Jun 28, 2017 everything seems to work fine.

**Comment by darold** [comment]
Ok, good news, I have done a test on my computer and all is working well too:
```
psql (10.4 (Ubuntu 10.4-2.pgdg18.04+1))

test=# CREATE EXTENSION uri;
CREATE EXTENSION
test=# create table table_name (name text, icon_path uri);
CREATE TABLE
test=# INSERT INTO table_name (name, icon_path)
    VALUES
('name_1', 'file:///home/GHNewbiee/icon_1.png'),
('name_2', 'file:///home/GHNewbiee/icon_2.png'),
('name_3', 'file:///home/GHNewbiee/icon_3.png');
INSERT 0 3
test=# select * from table_name;
  name  |             icon_path             
--------+-----------------------------------
 name_1 | file:///home/GHNewbiee/icon_1.png
 name_2 | file:///home/GHNewbiee/icon_2.png
 name_3 | file:///home/GHNewbiee/icon_3.png
```
