### ISSUE TITLE
missing dependency in readme

### ISSUE THREAD

**Issue by sourcenux** [darold/uri#4]
Hi,

when using Debian 11 you also need to install "libtool" and "autoconf" to successfully build uri. 

autoreconf -i
configure.ac:48: error: required file 'docs/Makefile.in' not found
Makefile.am:37: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:37:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:37:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:37:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:37:   its definition is in aclocal's search path.
t/lib/Makefile.am:17: error: Libtool library used but 'LIBTOOL' is undefined
t/lib/Makefile.am:17:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
t/lib/Makefile.am:17:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
t/lib/Makefile.am:17:   If 'LT_INIT' is in 'configure.ac', make sure
t/lib/Makefile.am:17:   its definition is in aclocal's search path.
uriparser/Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
uriparser/Makefile.am:8:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
uriparser/Makefile.am:8:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
uriparser/Makefile.am:8:   If 'LT_INIT' is in 'configure.ac', make sure
uriparser/Makefile.am:8:   its definition is in aclocal's search path.

**Comment by sourcenux** [comment]
okay. My bad. Could you please format the other packages' names like you formatted "apt-get install libcurl4-openssl-dev"?

**Comment by darold** [comment]
Commit 5799158 adds the apt/yum command to install all required packages. I have also change git:// by https:// reported in the other issue.

**Comment by sourcenux** [comment]
Thanks!
